services:
  backend:
    restart: always
    build:
      context: ./server
    volumes:
      - ${DB_REPO}:/app/
    networks:
      - sharednet

  frontend:
    restart: always
    build:
      context: ./client
      args:
        VITE_TITLE: ${TITLE}
        VITE_DATA_SERVER_URL: ${DATA_SERVER_URL}
        VITE_BACKEND_URL: http://backend:4001
    ports:
      - "${PORT}:3000"
    networks:
      - sharednet

networks:
  sharednet:
    name: my-shared-network
